"""Prompt templates for EZT -> COBOL conversion."""
from src.rules import general_rules_text, report_scaffolding_text

_GENERAL_RULES = general_rules_text()
_REPORT_SCAFFOLDING = report_scaffolding_text()

SYSTEM_PROMPT = f"""\
You are an Easytrieve (EZT) to COBOL conversion specialist for IBM mainframe environments.

## Easytrieve Language Reference

### Program Structure
1. Preamble (before JOB): FILE definitions then field/variable declarations
   (FILE/FIELD sections are converted separately — you will receive context
   showing the DATA DIVISION already generated from them)
2. JOB section: main processing logic
3. REPORT section: report layout and output (optional, may be multiple)

### JOB Section
  JOB INPUT filename
  JOB INPUT (file1 file2)
  JOB INPUT file1 OUTPUT file2
  ...logic...
  END-JOB  (or terminated by the next section keyword)

### Control Flow
  IF cond / ELSE / END-IF
  DO WHILE cond / DOEND
  DO UNTIL cond / DOEND
  PERFORM paragraph-name
  GO TO label
  STOP

### File Operations
  READ filename
  WRITE filename
  REWRITE filename
  DISPLAY field1 field2

### Conditions
  EQ, NE, GT, LT, GE, LE
  IF FOUND / IF NOTFOUND
  IF EOF / IF NOT EOF

### Data Manipulation
  MOVE source TO dest
  ADD value TO field
  SUBTRACT value FROM field
  COMPUTE result = expression

### REPORT Section
  REPORT reportname
    TITLE 'text'
    HEADING ...
    SEQUENCE field
    CONTROL field
    SUM field
    COUNT
    PRINT field1 field2 ...
    LINESIZE nn
    PAGESIZE nn
    FOOTING 'text'
  END-REPORT  (or terminated by the next section keyword)

## EZT → COBOL Logic Mapping (procedure division only)

### Range condition  (THRU)
  EZT:   IF FIELD 1 THRU 100
  COBOL: IF FIELD >= 1 AND FIELD <= 100

  EZT:   IF FIELD NOT 1 THRU 100
  COBOL: IF FIELD < 1 OR FIELD > 100

### Multi-value OR list
  EZT:   IF FIELD = 'A' 'B' 'C'          ← implicit OR
  COBOL: IF FIELD = 'A' OR FIELD = 'B' OR FIELD = 'C'

  EZT:   IF FIELD = (1 2 3)
  COBOL: IF FIELD = 1 OR FIELD = 2 OR FIELD = 3

### EOF test
  EZT:   IF EOF
  COBOL: Use the AT END clause inside READ ... AT END ... END-READ
         (do NOT test EOF with a separate IF outside the READ)

### VSAM auto-generated names (FILE-CONTROL is generated by Python)
  Every VSAM file gets two helper names you can reference directly in
  PROCEDURE DIVISION; do NOT redeclare them in WORKING-STORAGE:
    <FILENAME>-KEY        — the RECORD KEY field, declared in the FD
                            record layout.  Use this on the left of a
                            MOVE before a keyed READ, REWRITE, DELETE,
                            START, etc.
    WS-<FILENAME>-STATUS  — the FILE STATUS field (PIC X(2)), updated by
                            the runtime after every I/O call.

### VSAM found / not-found
  EZT:   IF FOUND
  COBOL: IF WS-<FILENAME>-STATUS = '00'

  EZT:   IF NOTFOUND
  COBOL: IF WS-<FILENAME>-STATUS = '23'

### STOP
  EZT:   STOP
  COBOL: STOP RUN

### Numeric / class test
  EZT:   IF FIELD NUMERIC
  COBOL: IF FIELD IS NUMERIC

  EZT:   IF FIELD ALPHANUMERIC
  COBOL: IF FIELD IS ALPHABETIC

  IMPORTANT: COBOL's numeric class test is the word NUMERIC.  There is
  NO  IS INTEGER  class test in COBOL — never emit  IF FIELD IS INTEGER.
  Use  IF FIELD IS NUMERIC  for "field contains digits / a valid number".

### Space / zero literals
  EZT:   IF FIELD = ' '   or   IF FIELD = SPACES
  COBOL: IF FIELD = SPACES

  EZT:   IF FIELD = 0   or   IF FIELD = ZERO
  COBOL: IF FIELD = ZERO

### PRINT (triggers report output)
  EZT:   PRINT report-name
  COBOL: PERFORM REPORT-NAME-PRINT-RTN   (or the equivalent report paragraph)

### GET (read VSAM record by key)
  EZT:   GET filename KEY (key-value)
  COBOL: MOVE key-value TO <FILENAME>-KEY
         READ FILENAME
             INVALID KEY MOVE '1' TO WS-<FILENAME>-STATUS
         END-READ
  (<FILENAME>-KEY is the RECORD KEY field auto-generated by FILE-CONTROL —
   see "VSAM auto-generated names" above.  If GET has no explicit key
   value, the key field is assumed to already be set by prior logic.)

### String / unstring
  EZT:   STRING  / UNSTRING  — translate directly to COBOL STRING / UNSTRING

### CALL
  EZT:   CALL program USING field1 field2
  COBOL: CALL 'PROGRAM' USING field1 field2

### SYSDATE / SYSTIME (current system date/time)
  EZT:   DISPLAY 'AS OF' SYSDATE SYSTIME
  COBOL: ACCEPT WS-SYSDATE FROM DATE YYYYMMDD
         ACCEPT WS-SYSTIME FROM TIME
         DISPLAY 'AS OF ' WS-SYSDATE ' ' WS-SYSTIME

  These COBOL ACCEPT verbs read the running system clock.  When the EZT
  program references SYSDATE or SYSTIME, declare the supporting WS items
  in your --- WORKING-STORAGE --- block and ACCEPT into them once near
  the start of MAIN-LOGIC (or in OPEN-FILES) before first use:
       01  WS-SYSDATE   PIC 9(8).      (YYYYMMDD)
       01  WS-SYSTIME   PIC 9(8).      (HHMMSSss)
  Then reference WS-SYSDATE / WS-SYSTIME everywhere the EZT used
  SYSDATE / SYSTIME — never emit SYSDATE or SYSTIME as raw identifiers
  in COBOL; they're EZT-only special registers and the compiler will
  reject them.

  If the program needs MM/DD/YYYY style output, declare an edited
  field and MOVE the components in:
       01  WS-SYSDATE-DISP.
           05  FILLER       PIC X(2)  VALUE SPACES.
           05  WS-SD-MM     PIC 9(2).
           05  FILLER       PIC X     VALUE '/'.
           05  WS-SD-DD     PIC 9(2).
           05  FILLER       PIC X     VALUE '/'.
           05  WS-SD-YYYY   PIC 9(4).
  …with the corresponding MOVE statements after the ACCEPT.

## COBOL Output Rules
1. Return ONLY the requested COBOL code. The very first character of your
   response must be the first character of the COBOL source. Do NOT emit any
   of the following:
     • reasoning, analysis, planning, or chain-of-thought
     • preamble such as "Here is the conversion:" or "Sure, ..."
     • explanations, summaries, or commentary after the code
     • markdown fences (```), headings, or any non-COBOL text
   Comments inside the COBOL source (lines with '*' in column 7) are allowed
   when they describe the code itself, but never use them to explain your
   reasoning process.
2. Standard COBOL column layout: Area A at col 8, Area B at col 12.
3. COBOL-85 compatible syntax.
4. Prefix working-storage items with WS-.
5. Prefix record fields with a short file abbreviation (e.g. CUST- for CUSTFILE).
6. PIC length must fit the VALUE — count the literal character by character,
   including every punctuation mark, parenthesis, hyphen, slash, and space.
   The quotes themselves are NOT counted; everything between them IS.
   Examples (count silently before writing the PIC):
     VALUE '(CC1164)'   → 8 chars  → PIC X(08)
     VALUE 'A/B-C 12'   → 8 chars  → PIC X(08)
     VALUE 'YES'        → 3 chars  → PIC X(03)
     VALUE 12345        → 5 digits → PIC 9(05)
     VALUE -99.95       → S9(02)V9(02)  (sign is implicit, not counted)
   When PIC < literal length the value is silently truncated by the compiler.
   When PIC > literal length the value is padded (spaces for X, zeros for 9) —
   that is acceptable but never undersize the PIC.

{_GENERAL_RULES}
"""

JOB_PROMPT = """\
Convert this Easytrieve JOB section to IBM Enterprise COBOL PROCEDURE DIVISION code.

━━ OUTPUT FORMAT ━━
Your response must consist of exactly two marker-delimited blocks in this order:

--- WORKING-STORAGE ---
[any 01-level WS items the procedure code below references that are NOT
 already in the provided DATA DIVISION context; leave this block empty
 if none are needed]
--- PROCEDURE ---
       PROCEDURE DIVISION.
       [procedure code]

The first characters of your response must be "--- WORKING-STORAGE ---".
Stop immediately after the last COBOL line; do not add a closing summary.

━━ WORKING-STORAGE BLOCK ━━
The DATA DIVISION context above already provides:
  • File structures (FD records and their sub-fields)
  • File status fields  WS-{FILENAME}-STATUS  (one per file)
  • VSAM record keys   {FILENAME}-KEY        (declared inside the FD,
    referenced from the SELECT clause; use as the key field for MOVE
    before READ / REWRITE / DELETE / START)
  • Items from FIELD_DEF / DEFINE

Declare a new 01-level item in the WORKING-STORAGE block ONLY when the
procedure code references a variable that is NOT in the provided context.

Common cases that need a declaration:
  • WS-EOF flag for AT END inside a READ loop (e.g. 01 WS-EOF PIC X VALUE 'N'.)
  • Work fields for intermediate COMPUTE results
  • Save areas for control-break logic
  • Local counters or accumulators not covered by file/field definitions

Rules for the WORKING-STORAGE block:
  • Do NOT duplicate items already in the provided context.
  • Do NOT include the "WORKING-STORAGE SECTION." header — only 01-level items.
  • Use standard column layout (01 at col 8).
  • PIC length must fit the VALUE — count the literal character by
    character (including parentheses, hyphens, slashes, spaces, punctuation).
    Quotes themselves are NOT counted; everything between them IS.
    Verify before you write the PIC:  VALUE '(CC1164)' has 8 chars, so
    PIC X(08) — not X(07).  See "COBOL Output Rules" #6 in the system
    prompt for the full rule and more examples.

━━ WHAT NOT TO OUTPUT ━━
Do NOT output any of the following:
  • Reasoning, analysis, planning, or chain-of-thought
  • Preamble such as "Here is the conversion:" or "I'll convert this..."
  • Explanations, summaries, or commentary after the code
  • Markdown fences (```), headings, or any non-COBOL text
  • IDENTIFICATION / ENVIRONMENT / DATA DIVISION headers
  • FILE SECTION, WORKING-STORAGE SECTION, or LINKAGE SECTION headers
  • Any item already defined in the provided DATA DIVISION context

━━ REQUIRED PROGRAM STRUCTURE ━━
The PROCEDURE DIVISION must always begin with a MAIN-PROCESS paragraph that
orchestrates the entire program by PERFORMing lower-level paragraphs in order.
Every PERFORM must use the THRU form so the exit paragraph is included.
STOP RUN must appear only inside MAIN-PROCESS, never in any other paragraph.

--- WORKING-STORAGE ---
       01  WS-EOF                          PIC X VALUE 'N'.
--- PROCEDURE ---
       PROCEDURE DIVISION.
       MAIN-PROCESS.
           PERFORM OPEN-FILES  THRU OPEN-FILES-EXIT
           PERFORM MAIN-LOGIC  THRU MAIN-LOGIC-EXIT
           PERFORM CLOSE-FILES THRU CLOSE-FILES-EXIT
           STOP RUN.
       MAIN-PROCESS-EXIT.
           EXIT.

       OPEN-FILES.
           OPEN INPUT INFILE
           IF WS-INFILE-STATUS > '00'
               DISPLAY 'ERROR OPENING INFILE STATUS: ' WS-INFILE-STATUS
               STOP RUN
           END-IF.
       OPEN-FILES-EXIT.
           EXIT.

       MAIN-LOGIC.
           READ INFILE
               AT END MOVE 'Y' TO WS-EOF
           END-READ
           PERFORM UNTIL WS-EOF = 'Y'
               PERFORM PROCESS-RECORD THRU PROCESS-RECORD-EXIT
               READ INFILE
                   AT END MOVE 'Y' TO WS-EOF
               END-READ
           END-PERFORM.
       MAIN-LOGIC-EXIT.
           EXIT.

       PROCESS-RECORD.
           ... processing logic ...
       PROCESS-RECORD-EXIT.
           EXIT.

       CLOSE-FILES.
           CLOSE INFILE.
       CLOSE-FILES-EXIT.
           EXIT.

Conditional paragraphs — omit when not applicable:
  • If the program has NO input or output files (e.g. JOB INPUT NULL), omit
    OPEN-FILES and CLOSE-FILES entirely and remove their PERFORM calls from
    MAIN-PROCESS.
  • If there is no file-reading loop (batch compute only), omit MAIN-LOGIC's
    READ loop and replace it with the processing statements directly.

━━ IBM ENTERPRISE COBOL STANDARDS ━━
Column layout (fixed format):
  • Paragraph names → Area A, column 8
  • All executable statements → Area B, column 12 (or deeper for nesting)
  • Nothing in columns 73+ (identification area — leave blank)

Period (full stop) rules — the most critical COBOL rule:
  • ONE period ends each paragraph: place it only on the LAST statement
  • NEVER put a period inside IF / EVALUATE / PERFORM / READ / WRITE blocks
  • Structured delimiters END-IF, END-EVALUATE, END-PERFORM, END-READ, END-WRITE
    terminate those blocks — the period comes only after the outermost END-xxx

Structured statements — always use scope terminators:
  • IF ... ELSE ... END-IF
  • EVALUATE ... WHEN ... END-EVALUATE
  • PERFORM ... END-PERFORM
  • READ ... AT END ... END-READ
  • WRITE ... INVALID KEY ... END-WRITE

Paragraph exit convention:
  • Every paragraph must be followed immediately by <PARA-NAME>-EXIT.
  • The exit paragraph contains only EXIT.
  • Every PERFORM must use the THRU form: PERFORM para THRU para-EXIT.
  • Applies to every paragraph including OPEN-FILES, CLOSE-FILES, MAIN-LOGIC, etc.

File open / close:
  • OPEN-FILES: after each OPEN, check WS-<FILENAME>-STATUS > '00';
    if true, DISPLAY an error message and STOP RUN.
  • CLOSE-FILES: one CLOSE statement per file, nothing else.
  • Use the exact WS-<FILENAME>-STATUS names from the DATA DIVISION context.

Prior converted context (DATA DIVISION already generated):
{context}

EZT JOB section:
{content}
"""

REPORT_PROMPT = f"""\
Convert this Easytrieve REPORT section to IBM Enterprise COBOL PROCEDURE DIVISION code.

{_REPORT_SCAFFOLDING}

━━ OUTPUT FORMAT ━━
Your response must consist of exactly two marker-delimited blocks in this order:

--- WORKING-STORAGE ---
[any 01-level WS items the procedure code below references that are NOT
 already in the provided DATA DIVISION context; leave this block empty
 if none are needed]
--- PROCEDURE ---
       [report procedure paragraphs — headings, detail print, control-break
        logic, end-of-report]

The first characters of your response must be "--- WORKING-STORAGE ---".
Stop immediately after the last COBOL line; do not add a closing summary.

━━ WORKING-STORAGE BLOCK ━━
Python has already generated these items in the DATA DIVISION context —
do NOT redeclare them:
  WS-PAGE-CTR, WS-LINE-CTR, WS-PAGE-LIMIT, WS-LINE-LIMIT, PRINT-REC
  WS-{{FIELD}}-TOT, WS-{{FIELD}}-TOT-D  (for each SUM field)
  WS-{{RPTNAME}}-CNT, WS-{{RPTNAME}}-CNT-D  (if COUNT present)

Declare a new 01-level item in the WORKING-STORAGE block ONLY when the
procedure code references a variable that is NOT in the provided context.

Common cases that need a declaration:
  • WS-{{RPTNAME}}-HDR / WS-{{RPTNAME}}-DTL print-line layouts
  • Control-break save areas (e.g. WS-PREV-{{FIELD}})
  • Edit-mask (PIC Z…) display fields not covered by SUM/COUNT
  • Work fields for intermediate COMPUTE results

Rules for the WORKING-STORAGE block:
  • Do NOT duplicate items already in the provided context.
  • Do NOT include the "WORKING-STORAGE SECTION." header — only 01-level items.
  • Use standard column layout (01 at col 8).
  • PIC length must fit the VALUE — count the literal character by
    character (including parentheses, hyphens, slashes, spaces, punctuation).
    Quotes themselves are NOT counted; everything between them IS.
    Verify before you write the PIC:  VALUE '(CC1164)' has 8 chars, so
    PIC X(08) — not X(07).  See "COBOL Output Rules" #6 in the system
    prompt for the full rule and more examples.

━━ WHAT NOT TO OUTPUT ━━
Do NOT output any of the following:
  • Reasoning, analysis, planning, or chain-of-thought
  • Preamble such as "Here is the conversion:" or "I'll convert this..."
  • Explanations, summaries, or commentary after the code
  • Markdown fences (```), headings, or any non-COBOL text
  • IDENTIFICATION / ENVIRONMENT / DATA DIVISION headers
  • FILE SECTION, WORKING-STORAGE SECTION, or LINKAGE SECTION headers
  • Any item already defined in the provided DATA DIVISION context

━━ IBM ENTERPRISE COBOL STANDARDS ━━
Column layout (fixed format):
  • Paragraph names and division/section headers → Area A, column 8
  • All executable statements → Area B, column 12 (or deeper for nesting)
  • Nothing in columns 73+ (identification area — leave blank)

Period (full stop) rules — the most critical COBOL rule:
  • ONE period ends each paragraph: place it only on the LAST statement of the paragraph
  • NEVER put a period inside IF / EVALUATE / PERFORM / READ / WRITE blocks
  • Structured delimiters END-IF, END-EVALUATE, END-PERFORM, END-READ, END-WRITE
    terminate those blocks — the period comes only after the outermost END-xxx

Structured statements — always use scope terminators:
  • IF ... ELSE ... END-IF          (no period inside)
  • EVALUATE ... WHEN ... END-EVALUATE
  • PERFORM ... END-PERFORM         (inline PERFORM must have END-PERFORM)
  • READ ... AT END ... END-READ
  • WRITE ... INVALID KEY ... END-WRITE

Paragraph exit convention — every paragraph must have a matching exit paragraph:
  • Name it <PARA-NAME>-EXIT and place it immediately after the paragraph body.
  • The exit paragraph contains only the single word EXIT followed by a period.
  • Every PERFORM must use the THRU form: PERFORM para THRU para-EXIT.
  • This applies to every paragraph that can be PERFORMed.

       {{RPTNAME}}-DETAIL.
           MOVE CUSTNO   TO WS-DTL-CUSTNO
           MOVE CUSTNAME TO WS-DTL-CUSTNAME
           WRITE {{OUTFILE}}-REC FROM WS-{{RPTNAME}}-DTL
               AFTER ADVANCING 1 LINE
           ADD 1 TO WS-LINE-CTR
           IF WS-LINE-CTR >= WS-LINE-LIMIT
               PERFORM {{RPTNAME}}-HEADINGS THRU {{RPTNAME}}-HEADINGS-EXIT
           END-IF.
       {{RPTNAME}}-DETAIL-EXIT.
           EXIT.

Prior converted context:
{{context}}

EZT REPORT section:
{{content}}
"""


LOGIC_PROMPT = f"""\
Convert this Easytrieve program's executable logic — one JOB section plus
zero or more REPORT sections — into a SINGLE, unified IBM Enterprise COBOL
PROCEDURE DIVISION.  Every paragraph from every section belongs in the
same procedure block; emit each one exactly once.

{_REPORT_SCAFFOLDING}

━━ OUTPUT FORMAT ━━
Your response must consist of exactly two marker-delimited blocks in this order:

--- WORKING-STORAGE ---
[any 01-level WS items the procedure code below references that are NOT
 already in the provided DATA DIVISION context; leave this block empty
 if none are needed]
--- PROCEDURE ---
       PROCEDURE DIVISION.
       [unified procedure code — JOB paragraphs first, then each REPORT's
        paragraphs; every paragraph appears exactly once]

The first characters of your response must be "--- WORKING-STORAGE ---".
Stop immediately after the last COBOL line; do not add a closing summary.

━━ WORKING-STORAGE BLOCK ━━
The DATA DIVISION context above already provides:
  • File structures (FD records and their sub-fields)
  • File status fields  WS-<FILENAME>-STATUS  (one per file)
  • VSAM record keys   <FILENAME>-KEY        (declared inside the FD)
  • Items from FIELD_DEF / DEFINE
  • Per-report WS already generated deterministically by Python:
        WS-PAGE-CTR, WS-LINE-CTR, WS-PAGE-LIMIT, WS-LINE-LIMIT, PRINT-REC
        WS-{{FIELD}}-TOT, WS-{{FIELD}}-TOT-D    (for each SUM field)
        WS-{{RPTNAME}}-CNT, WS-{{RPTNAME}}-CNT-D  (if COUNT present)
        WS-{{RPTNAME}}-TITLE[-NN]  — one per TITLE [NN] 'text' directive;
                                     -NN suffix when EZT supplied a line
                                     number, bare WS-{{RPTNAME}}-TITLE when
                                     it didn't.  Centered on LINESIZE.
        WS-{{RPTNAME}}-HDG[-NN]    — one per HEADING [NN] 'text', or a
                                     single auto-generated column-header
                                     row when only PRINT is used.
        WS-{{RPTNAME}}-LINE-NN     — one per LINE NN ... directive.
                                     Centered text when 'text' is given;
                                     positioned subfields for the form
                                     LINE NN COL c FIELD COL c FIELD ...
                                     Field-reference subfields are named
                                     WS-{{RPT}}-L{{NN}}-{{FIELD-STEM}}
                                     (similar T{{NN}} for TITLE,
                                     H{{NN}} for HDG, F{{NN}} for FOOT).
        WS-{{RPTNAME}}-DTL         — from PRINT field list (one
                                     WS-DTL-<FLD> subfield per printed
                                     field, already sized to that field's
                                     width).
        WS-{{RPTNAME}}-FOOT[-NN]   — one per FOOTING [NN] 'text'.
        WS-<CTRL>-SAVE             — from CONTROL <field>

Declare a new 01-level item in the WORKING-STORAGE block ONLY when the
procedure code references a variable that is NOT in the provided context.
The print-line layouts above are pre-built — you only need to MOVE the
source fields into the generated subfields and WRITE the FD record
FROM the layout.

Above every print-line layout that contains field references the DATA
DIVISION context has comment lines of the form:
       * <LAYOUT-NAME> MOVE-targets:
       *   <EZT-FIELD-NAME> PIC ... -> <GENERATED-SUBFIELD-NAME>
Use these mappings verbatim — the LEFT-hand name is the EZT source you
read from, the RIGHT-hand name is the target subfield that already
exists in WORKING-STORAGE and that you must MOVE into.  Do NOT invent
your own subfield names.  COBOL identifiers cannot exceed 30 characters,
so the generated targets are already sized for you.

━━ TRANSLATE ONLY WHAT'S IN THE SOURCE ━━
The procedure code must mirror the EZT logic as-given.  Do NOT invent
behaviour that is not present in the EZT source:
  • No extra validation, error handling, or defensive checks beyond what
    EZT explicitly does.
  • No extra paragraphs, computations, or branches that EZT didn't ask for.
  • Do NOT re-declare a variable that is already in the allow-list below.
  • If two of your paragraphs would need the same WS item, declare it
    ONCE in your --- WORKING-STORAGE --- block; the assembler rejects
    duplicate 01-level names.

The only scaffolding you may add beyond the EZT statements is the
required MAIN-PROCESS / OPEN-FILES / MAIN-LOGIC / CLOSE-FILES skeleton
documented above (and any <RPT>-HEADINGS / <RPT>-DETAIL / <RPT>-END
paragraphs required by the REPORT scaffolding rules).

━━ UNSUPPORTED COBOL FUNCTIONS ━━
Some environments don't support intrinsic functions.  In particular,
NEVER emit  FUNCTION MOD(x, y)  — many compilers reject it.  Use a
COMPUTE-based modulo instead:
       COMPUTE WS-REM = WS-X - (FUNCTION INTEGER (WS-X / WS-Y)) * WS-Y
or, if FUNCTION INTEGER is also unavailable, materialise the quotient
in an integer working-storage field and subtract:
       DIVIDE WS-X BY WS-Y GIVING WS-Q
       COMPUTE WS-REM = WS-X - (WS-Q * WS-Y)

━━ IDENTIFIER ALLOW-LIST (CRITICAL) ━━
The end of the context block contains an "AVAILABLE WORKING-STORAGE +
FILE-SECTION IDENTIFIERS" list.  EVERY identifier you reference in the
procedure code (operands of MOVE, ADD, COMPUTE, IF, READ, WRITE, etc.)
MUST either:
  (a) appear verbatim in that list, OR
  (b) be a new 01-level item that YOU declare in the
      --- WORKING-STORAGE --- block of your response.

Never invent a variable name that is neither in the allow-list nor
declared in your WS block — the compiler will reject it.  If an EZT
field has a long name that gets truncated to ≤30 chars in the
allow-list, use the truncated form (it is the actual generated name).

Common cases that DO need a declaration:
  • WS-EOF flag for AT END inside a READ loop
  • Work fields for intermediate COMPUTE results
  • Edit-mask (PIC Z…) display fields not covered by SUM/COUNT

Rules for the WORKING-STORAGE block:
  • Do NOT duplicate items already in the provided context.
  • Do NOT include the "WORKING-STORAGE SECTION." header — only 01-level items.
  • COLUMN LAYOUT IS MANDATORY:
      - 01-level items MUST begin at column 8 (precede them with EXACTLY
        7 spaces).  Never start a 01 at column 1.
      - Sub-levels (05, 10, 15, …) MUST begin at column 12 (precede them
        with EXACTLY 11 spaces).  Never start a sub-level at column 1.
    Example (count the spaces before each level number):

           01  WS-EOF                      PIC X VALUE 'N'.
           01  WS-RPT-DTL.
               05  WS-DTL-CUSTNO           PIC 9(5).
               05  WS-DTL-CUSTNAME         PIC X(30).

  • PIC length must fit the VALUE — count the literal character by
    character (including parentheses, hyphens, slashes, spaces, punctuation).
    See "COBOL Output Rules" #6 in the system prompt for the full rule.

━━ WHAT NOT TO OUTPUT ━━
Do NOT output any of the following:
  • Reasoning, analysis, planning, or chain-of-thought
  • Preamble such as "Here is the conversion:" or "I'll convert this..."
  • Explanations, summaries, or commentary after the code
  • Markdown fences (```), headings, or any non-COBOL text
  • IDENTIFICATION / ENVIRONMENT / DATA DIVISION headers
  • FILE SECTION, WORKING-STORAGE SECTION, or LINKAGE SECTION headers
  • Any item already defined in the provided DATA DIVISION context
  • Any paragraph emitted more than once across the JOB and REPORT sections
  • 01-level or sub-level data items starting in column 1 (Area A
    column 8 is required for 01, Area B column 12 for sub-levels)

━━ REQUIRED PROGRAM STRUCTURE ━━
The PROCEDURE DIVISION must always begin with a MAIN-PROCESS paragraph
that orchestrates the entire program by PERFORMing lower-level paragraphs
in order.  Every PERFORM must use the THRU form so the exit paragraph is
included.  STOP RUN must appear only inside MAIN-PROCESS.

Paragraph naming — IMPORTANT:
  COBOL reserved words CANNOT be used as paragraph names.  Never emit a
  paragraph called INITIAL, INITIALIZE, TERMINATE, START, END, DATA,
  SECTION, OPEN, CLOSE, READ, WRITE, MOVE, IF, DISPLAY, COMPUTE, etc.
  Use a descriptive suffix instead:
       BAD:   INITIAL.   /   TERMINATE.
       GOOD:  INIT-RTN.  /   TERM-RTN.  /  WRAP-UP.  /  CLEANUP-RTN.
  When in doubt, append -RTN, -PARA, or -PROCESS to the verb.

JOB paragraphs come first:
       MAIN-PROCESS.
           PERFORM OPEN-FILES   THRU OPEN-FILES-EXIT
           PERFORM MAIN-LOGIC   THRU MAIN-LOGIC-EXIT
           PERFORM CLOSE-FILES  THRU CLOSE-FILES-EXIT
           STOP RUN.
       MAIN-PROCESS-EXIT.
           EXIT.

       OPEN-FILES.
           OPEN INPUT INFILE
           IF WS-INFILE-STATUS > '00'
               DISPLAY 'ERROR OPENING INFILE STATUS: ' WS-INFILE-STATUS
               STOP RUN
           END-IF.
       OPEN-FILES-EXIT.
           EXIT.

       MAIN-LOGIC.
           READ INFILE
               AT END MOVE 'Y' TO WS-EOF
           END-READ
           PERFORM UNTIL WS-EOF = 'Y'
               PERFORM PROCESS-RECORD THRU PROCESS-RECORD-EXIT
               READ INFILE
                   AT END MOVE 'Y' TO WS-EOF
               END-READ
           END-PERFORM.
       MAIN-LOGIC-EXIT.
           EXIT.

       PROCESS-RECORD.
           ... per-record processing; any PRINT <rptname> in EZT becomes
               PERFORM <RPTNAME>-PRINT-RTN THRU <RPTNAME>-PRINT-RTN-EXIT
       PROCESS-RECORD-EXIT.
           EXIT.

       CLOSE-FILES.
           CLOSE INFILE.
       CLOSE-FILES-EXIT.
           EXIT.

Then the REPORT paragraphs for EACH report (use the report's name as the
prefix); see "REPORT Section Conversion Rules" above for the full list.

Conditional paragraphs — omit when not applicable:
  • If the program has NO input or output files (e.g. JOB INPUT NULL),
    omit OPEN-FILES and CLOSE-FILES entirely and remove their PERFORM
    calls from MAIN-PROCESS.
  • If there is no file-reading loop (batch compute only), omit
    MAIN-LOGIC's READ loop and replace it with the processing statements
    directly.

━━ IBM ENTERPRISE COBOL STANDARDS ━━
Column layout (fixed format):
  • Paragraph names → Area A, column 8
  • All executable statements → Area B, column 12 (or deeper for nesting)
  • Nothing in columns 73+ (identification area — leave blank)

Period (full stop) rules — the most critical COBOL rule:
  • ONE period ends each paragraph: place it only on the LAST statement.
  • That trailing period is MANDATORY before the next paragraph header.
    Without it the compiler glues the next paragraph header onto the
    previous statement and the program fails to compile.

       WRONG (missing '.' before MAIN-PROCESS-EXIT):
           MAIN-PROCESS.
               PERFORM OPEN-FILES THRU OPEN-FILES-EXIT
               STOP RUN
           MAIN-PROCESS-EXIT.
               EXIT.

       RIGHT:
           MAIN-PROCESS.
               PERFORM OPEN-FILES THRU OPEN-FILES-EXIT
               STOP RUN.
           MAIN-PROCESS-EXIT.
               EXIT.

  • NEVER put a period inside IF / EVALUATE / PERFORM / READ / WRITE blocks.
  • Structured delimiters END-IF, END-EVALUATE, END-PERFORM, END-READ, END-WRITE
    terminate those blocks — the period comes only after the outermost END-xxx,
    and that period is still required before the next paragraph header.

Structured statements — always use scope terminators:
  • IF ... ELSE ... END-IF
  • EVALUATE ... WHEN ... END-EVALUATE
  • PERFORM ... END-PERFORM
  • READ ... AT END ... END-READ
  • WRITE ... INVALID KEY ... END-WRITE

Paragraph exit convention:
  • Every paragraph must be followed immediately by <PARA-NAME>-EXIT.
  • The exit paragraph contains only EXIT.
  • Every PERFORM must use the THRU form: PERFORM para THRU para-EXIT.

File open / close:
  • OPEN-FILES: after each OPEN, check WS-<FILENAME>-STATUS > '00';
    if true, DISPLAY an error message and STOP RUN.
  • CLOSE-FILES: one CLOSE statement per file, nothing else.
  • Use the exact WS-<FILENAME>-STATUS names from the DATA DIVISION context.

Prior converted context (DATA DIVISION already generated):
{{context}}

EZT logic sections (JOB + REPORTs):
{{content}}
"""
