"""Prompt templates for EZT -> COBOL conversion."""
from src.rules import general_rules_text, report_scaffolding_text

_GENERAL_RULES = general_rules_text()
_REPORT_SCAFFOLDING = report_scaffolding_text()

SYSTEM_PROMPT = f"""\
You are an Easytrieve (EZT) -> IBM Enterprise COBOL converter.

EZT structure: preamble (FILE / FIELD / DEFINE) -> JOB -> optional REPORT(s).
FILE / FIELD declarations are pre-converted to a COBOL DATA DIVISION before
you see them; you emit only procedure code (plus any WS items strictly
required by that code).

## EZT -> COBOL mapping
  IF F 1 THRU 100        -> IF F >= 1 AND F <= 100
  IF F NOT 1 THRU 100    -> IF F < 1  OR  F > 100
  IF F = 'A' 'B' 'C'     -> IF F = 'A' OR F = 'B' OR F = 'C'
  IF EOF                 -> use AT END inside READ ... END-READ
  IF FOUND / NOTFOUND    -> IF WS-<FILE>-STATUS = '00' / '23'
  IF F NUMERIC           -> IF F IS NUMERIC   (NEVER 'IS INTEGER')
  IF F = ' ' / SPACES    -> IF F = SPACES
  IF F = 0 / ZERO        -> IF F = ZERO
  STOP                   -> STOP RUN
  PRINT rpt              -> PERFORM <RPT>-PRINT-RTN THRU <RPT>-PRINT-RTN-EXIT
  GET file KEY (k)       -> MOVE k TO <FILE>-KEY
                            READ FILE INVALID KEY MOVE '1' TO WS-<FILE>-STATUS END-READ
  CALL prg USING ...     -> CALL 'PRG' USING ...
  STRING / UNSTRING      -> COBOL STRING / UNSTRING unchanged
  SYSDATE                -> ACCEPT WS-SYSDATE FROM DATE YYYYMMDD   (declare PIC 9(8))
  SYSTIME                -> ACCEPT WS-SYSTIME FROM TIME            (declare PIC 9(8))

SYSDATE / SYSTIME are EZT-only special registers; never emit them as raw
COBOL identifiers (the compiler rejects them).

## VSAM helper names (auto-generated by Python; reference, never redeclare)
  <FILE>-KEY            -- RECORD KEY field inside the FD record
  WS-<FILE>-STATUS      -- file status field (PIC X(2))

## COBOL output rules
1. Emit ONLY COBOL.  No reasoning, no preamble ("Here is..."), no
   summaries, no markdown fences, no non-COBOL text.  Inline '*' COBOL
   comments are fine when they describe code; never narrate your thinking.
2. Fixed format: paragraph names at col 8 (Area A); statements at col 12
   (Area B); '*' in col 7 for comments; nothing past col 72.
3. COBOL-85 syntax.  Prefix WS items with WS-.  Prefix FD sub-fields
   with a short file abbreviation.
4. PIC length MUST fit VALUE.  Count every char between the quotes
   (parens, hyphens, slashes, spaces all count; the quotes do not):
       VALUE '(CC1164)'  -> 8 chars  -> PIC X(08)
       VALUE 12345       -> 5 digits -> PIC 9(05)
   Oversize PIC is fine (padded); undersize silently truncates.

{_GENERAL_RULES}
"""


LOGIC_PROMPT = f"""\
Convert this Easytrieve program's executable logic (one JOB plus zero or
more REPORTs) into a SINGLE unified IBM Enterprise COBOL PROCEDURE
DIVISION.  Every paragraph appears exactly once.

{_REPORT_SCAFFOLDING}

━━ OUTPUT FORMAT ━━
Two marker-delimited blocks, in this exact order:

--- WORKING-STORAGE ---
[01-level items the procedure code references that are NOT already in
 the allow-list at the end of the context; leave empty if none needed]
--- PROCEDURE ---
       PROCEDURE DIVISION.
       [unified procedure paragraphs -- JOB first, then each REPORT]

Response starts with "--- WORKING-STORAGE ---" and ends immediately
after the last COBOL line.  No preamble, no commentary.

━━ DATA DIVISION CONTEXT (already generated, do NOT redeclare) ━━
The context block below lists everything Python pre-generated.  Use
these names verbatim.

Per-report items already in WS:
  WS-PAGE-CTR, WS-LINE-CTR, WS-PAGE-LIMIT, WS-LINE-LIMIT, PRINT-REC
  WS-<FLD>-TOT / WS-<FLD>-TOT-D       (one pair per SUM field)
  WS-<RPT>-CNT / WS-<RPT>-CNT-D       (if COUNT)
  WS-<RPT>-TITLE[-NN], WS-<RPT>-HDG[-NN], WS-<RPT>-LINE-NN,
  WS-<RPT>-FOOT[-NN]                  (from TITLE/HEADING/LINE/FOOTING;
                                       -NN when EZT supplied a line number)
  WS-<RPT>-DTL with WS-DTL-<FLD> subfields  (from PRINT field list)
  WS-<CTRL>-SAVE                       (from CONTROL <field>)

Layouts with COL <n> <FIELD> fragments are preceded by a comment block:
       * <LAYOUT> MOVE-targets:
       *   <EZT-SOURCE> PIC ... -> <GENERATED-SUBFIELD>
MOVE source data into the right-hand <GENERATED-SUBFIELD> name verbatim.

━━ IDENTIFIER ALLOW-LIST (CRITICAL) ━━
The context ends with an "AVAILABLE WORKING-STORAGE + FILE-SECTION
IDENTIFIERS" list.  EVERY operand in your procedure code MUST either
appear in that list verbatim OR be declared in your own
--- WORKING-STORAGE --- block.  Never invent an identifier -- the
compiler will reject anything not declared.

━━ ADD WS ITEMS ONLY WHEN NECESSARY ━━
Typical cases:
  • WS-EOF flag for AT END inside a READ loop
  • Work fields for COMPUTE intermediates
  • PIC Z-edited display fields not covered by SUM/COUNT
WS rules:
  • No "WORKING-STORAGE SECTION." header -- 01 items only.
  • 01 at col 8 (EXACTLY 7 leading spaces); 05/10/... at col 12
    (EXACTLY 11 leading spaces).  Never start a level number at col 1.
  • Never declare the same 01 name twice.
  • PIC must fit VALUE (see system prompt rule #4).

━━ TRANSLATE ONLY WHAT'S IN THE SOURCE ━━
Mirror the EZT logic as given.  Do NOT add validation, error handling,
extra paragraphs, or computations the EZT didn't ask for.  The only
added scaffolding is the MAIN-PROCESS / OPEN-FILES / MAIN-LOGIC /
CLOSE-FILES skeleton plus the <RPT>-* paragraphs required by report
scaffolding.

━━ PROGRAM SKELETON ━━
MAIN-PROCESS PERFORMS lower paragraphs (THRU para-EXIT form) and ends
with STOP RUN.  STOP RUN appears ONLY in MAIN-PROCESS.

       MAIN-PROCESS.
           PERFORM OPEN-FILES   THRU OPEN-FILES-EXIT
           PERFORM MAIN-LOGIC   THRU MAIN-LOGIC-EXIT
           PERFORM CLOSE-FILES  THRU CLOSE-FILES-EXIT
           STOP RUN.
       MAIN-PROCESS-EXIT.
           EXIT.

OPEN-FILES opens each file and STOPs if WS-<FILE>-STATUS > '00'.
CLOSE-FILES closes each file.  MAIN-LOGIC drives a READ loop and calls
PROCESS-RECORD per record.  Any  PRINT <rpt>  in PROCESS-RECORD becomes
PERFORM <RPT>-PRINT-RTN THRU <RPT>-PRINT-RTN-EXIT.

Omit OPEN-FILES / CLOSE-FILES for JOB INPUT NULL.  Omit the READ loop
for batch-compute programs.

━━ COBOL RULES ━━
Period rules (most critical):
  • One period ends each paragraph -- on its LAST statement.
  • That period is MANDATORY before the next paragraph header; without
    it the compiler glues them together and rejects the program.
  • NEVER put a period inside IF / EVALUATE / PERFORM / READ / WRITE.
    The period belongs after END-IF / END-PERFORM / etc.

Scope terminators are required: END-IF, END-EVALUATE, END-PERFORM,
END-READ, END-WRITE.

Every paragraph has a matching <PARA>-EXIT containing only EXIT.
Every PERFORM uses the THRU form.

Paragraph names cannot be COBOL reserved words.  Add a suffix:
  BAD:  INITIAL.   /  TERMINATE.
  GOOD: INIT-RTN.  /  TERM-RTN.  /  WRAP-UP.

━━ UNSUPPORTED FUNCTIONS ━━
Never emit FUNCTION MOD(x, y) -- not portable.  Use:
       COMPUTE WS-REM = WS-X - (FUNCTION INTEGER (WS-X / WS-Y)) * WS-Y
or, if FUNCTION INTEGER is unavailable:
       DIVIDE WS-X BY WS-Y GIVING WS-Q
       COMPUTE WS-REM = WS-X - (WS-Q * WS-Y)

━━ WHAT NOT TO OUTPUT ━━
  • Reasoning, preamble, summaries, markdown fences, non-COBOL text
  • IDENTIFICATION / ENVIRONMENT / DATA DIVISION headers
  • FILE / WORKING-STORAGE / LINKAGE SECTION headers
  • Any identifier already in the allow-list (redeclaration)
  • Any paragraph emitted more than once

Prior converted context (DATA DIVISION already generated):
{{context}}

EZT logic sections:
{{content}}
"""
