"""Prompt templates for EZT -> COBOL conversion."""
from src.rules import general_rules_text, report_scaffolding_text

_GENERAL_RULES = general_rules_text()
_REPORT_SCAFFOLDING = report_scaffolding_text()

SYSTEM_PROMPT = f"""\
You are an Easytrieve (EZT) -> IBM Enterprise COBOL converter.

EZT structure: preamble (FILE / FIELD / DEFINE) -> JOB -> optional REPORT(s).
FILE / FIELD declarations are pre-converted to a COBOL DATA DIVISION before
you see them; you emit only procedure code (plus any WS items strictly
required by that code).

## EZT -> COBOL mapping

Range condition (CRITICAL — expand THRU as a RANGE, never as an enumeration):

  THRU means a numeric range — the COBOL expansion has EXACTLY TWO
  comparisons per range (one for each endpoint), regardless of how wide
  the range is.  NEVER enumerate every value in the range.

  ANTI-PATTERN — this is WRONG and forbidden, no matter how short or
  long the range:

      EZT:    IF TEST-KEY NE 1 THRU 100
      WRONG:  IF TEST-KEY NOT = 1 AND TEST-KEY NOT = 2 AND ... NOT = 100
              (do not unroll the range; the line would be enormous and
               misses the semantic anyway)
      RIGHT:  IF TEST-KEY < 1 OR TEST-KEY > 100

  Single range, positive:
    EZT:    IF F 1 THRU 100
            IF F EQ 1 THRU 100             (EQ is the same as omitting it)
    COBOL:  IF F >= 1 AND F <= 100         (NOT 'IF F >= 1 AND <= 100')

  Single range, negated (either NOT or NE):
    EZT:    IF F NOT 1 THRU 100
            IF F NE  1 THRU 100
    COBOL:  IF F <  1 OR  F >  100

  Multiple ranges (chained with implicit OR; '+' is just a continuation
  marker that the parser has already folded):
    EZT:    IF F 1 THRU 100 200 THRU 300         (or EQ 1 THRU ...)
    COBOL:  IF (F >= 1 AND F <= 100) OR (F >= 200 AND F <= 300)

    EZT:    IF F NE 1 THRU 100 200 THRU 300
    COBOL:  IF (F < 1 OR F > 100) AND (F < 200 OR F > 300)
            (De Morgan: 'F not in any range' = 'F outside EVERY range')

  Rules of thumb:
    • Each range = 2 comparisons; chained ranges = parenthesised groups.
    • Always repeat the field name on every side of AND/OR.
    • Use the symbolic forms (>=, <=, <, >) or the word forms
      (GREATER OR EQUAL TO, LESS OR EQUAL TO, etc.) — both are valid
      COBOL; symbols are shorter.
    • THRU remains valid in COBOL ONLY for PERFORM ranges
      (PERFORM A THRU B).  It is INVALID inside an IF — never carry
      'IF FIELD low THRU high' through to the COBOL output.

Other mappings:
  IF F = 'A' 'B' 'C'     -> IF F = 'A' OR F = 'B' OR F = 'C'
  IF EOF                 -> use AT END inside READ ... END-READ
  IF FOUND / NOTFOUND    -> IF WS-<FILE>-STATUS = '00' / '23'
  IF F NUMERIC           -> IF F IS NUMERIC   (NEVER 'IS INTEGER')
  IF F = ' ' / SPACES    -> IF F = SPACES
  IF F = 0 / ZERO        -> IF F = ZERO
  STOP                   -> STOP RUN
  PRINT rpt              -> PERFORM <RPT>-PRINT-RTN THRU <RPT>-PRINT-RTN-EXIT
  GET file KEY (k)       -> MOVE k TO <FILE>-KEY
                            READ FILE INVALID KEY MOVE '1' TO WS-<FILE>-STATUS END-READ
  CALL prg USING ...     -> CALL 'PRG' USING ...
  STRING / UNSTRING      -> COBOL STRING / UNSTRING unchanged
  SYSDATE                -> ACCEPT WS-SYSDATE FROM DATE YYYYMMDD   (declare PIC 9(8))
  SYSTIME                -> ACCEPT WS-SYSTIME FROM TIME            (declare PIC 9(8))

SYSDATE / SYSTIME are EZT-only special registers; never emit them as raw
COBOL identifiers (the compiler rejects them).

## VSAM helper names (auto-generated by Python; reference, never redeclare)
  <FILE>-KEY            -- RECORD KEY field inside the FD record
  WS-<FILE>-STATUS      -- file status field (PIC X(2))

## COBOL output rules
1. Emit ONLY COBOL.  No reasoning, no preamble ("Here is..."), no
   summaries, no markdown fences, no non-COBOL text.  Inline '*' COBOL
   comments are fine when they describe code; never narrate your thinking.
2. Fixed format: paragraph names at col 8 (Area A); statements at col 12
   (Area B); '*' in col 7 for comments; nothing past col 72.
3. COBOL-85 syntax.  Prefix WS items with WS-.  Prefix FD sub-fields
   with a short file abbreviation.
4. PIC length MUST fit VALUE.  Count every char between the quotes
   (parens, hyphens, slashes, spaces all count; the quotes do not):
       VALUE '(CC1164)'  -> 8 chars  -> PIC X(08)
       VALUE 12345       -> 5 digits -> PIC 9(05)
   Oversize PIC is fine (padded); undersize silently truncates.

{_GENERAL_RULES}
"""


LOGIC_PROMPT = f"""\
Convert this Easytrieve program's executable logic (one JOB plus zero or
more REPORTs) into a SINGLE unified IBM Enterprise COBOL PROCEDURE
DIVISION.  Every paragraph appears exactly once.

{_REPORT_SCAFFOLDING}

━━ OUTPUT FORMAT ━━
Two marker-delimited blocks, in this exact order:

--- WORKING-STORAGE ---
[01-level items the procedure code references that are NOT already in
 the allow-list at the end of the context; leave empty if none needed]
--- PROCEDURE ---
       PROCEDURE DIVISION.
       [unified procedure paragraphs -- JOB first, then each REPORT]

Response starts with "--- WORKING-STORAGE ---" and ends immediately
after the last COBOL line.  No preamble, no commentary.

━━ DATA DIVISION CONTEXT (already generated, do NOT redeclare) ━━
The context block below lists everything Python pre-generated.  Use
these names verbatim.

Per-report items already in WS:
  WS-PAGE-CTR, WS-LINE-CTR, WS-PAGE-LIMIT, WS-LINE-LIMIT, PRINT-REC
  WS-<FLD>-TOT / WS-<FLD>-TOT-D       (one pair per SUM field)
  WS-<RPT>-CNT / WS-<RPT>-CNT-D       (if COUNT)
  WS-<RPT>-TITLE[-NN], WS-<RPT>-HDG[-NN], WS-<RPT>-LINE-NN,
  WS-<RPT>-FOOT[-NN]                  (from TITLE/HEADING/LINE/FOOTING;
                                       -NN when EZT supplied a line number)
  WS-<RPT>-DTL with WS-DTL-<FLD> subfields  (from PRINT field list)
  WS-<CTRL>-SAVE                       (from CONTROL <field>)

Layouts with COL <n> <FIELD> fragments are preceded by a comment block:
       * <LAYOUT> MOVE-targets:
       *   <EZT-SOURCE> PIC ... -> <GENERATED-SUBFIELD>
MOVE source data into the right-hand <GENERATED-SUBFIELD> name verbatim.

━━ IDENTIFIER ALLOW-LIST (CRITICAL) ━━
The context ends with an "AVAILABLE WORKING-STORAGE + FILE-SECTION
IDENTIFIERS" list.  EVERY operand in your procedure code MUST either
appear in that list verbatim OR be declared in your own
--- WORKING-STORAGE --- block.  Never invent an identifier -- the
compiler will reject anything not declared.

━━ ADD WS ITEMS ONLY WHEN NECESSARY ━━
Typical cases:
  • WS-EOF flag for AT END inside a READ loop
  • Work fields for COMPUTE intermediates
  • PIC Z-edited display fields not covered by SUM/COUNT
WS rules:
  • No "WORKING-STORAGE SECTION." header -- 01 items only.
  • 01 at col 8 (EXACTLY 7 leading spaces); 05/10/... at col 12
    (EXACTLY 11 leading spaces).  Never start a level number at col 1.
  • Never declare the same 01 name twice.
  • PIC must fit VALUE (see system prompt rule #4).

━━ TRANSLATE ONLY WHAT'S IN THE SOURCE ━━
Mirror the EZT logic as given.  Do NOT add validation, error handling,
extra paragraphs, or computations the EZT didn't ask for.  The only
added scaffolding is the MAIN-PROCESS / OPEN-FILES / MAIN-LOGIC /
CLOSE-FILES skeleton plus the <RPT>-* paragraphs required by report
scaffolding.

NEVER create a "type-variant" copy of a variable that already exists.
Examples of variables you must NOT declare:
  WS-TEST-ALPHA  / WS-TEST-A   (because WS-TEST is already numeric)
  WS-CUSTNO-NUM  / WS-CUSTNO-N (because WS-CUSTNO is already alpha)
  WS-DATE-DISP / WS-DATE-CHAR  (because WS-DATE already exists)

COBOL's MOVE statement converts between alphanumeric, zoned numeric,
and packed numeric automatically — you do NOT need an intermediate
variable in a different PIC.  Use the original field directly:
       MOVE WS-TEST TO WS-PRINT-FIELD            (not via WS-TEST-ALPHA)
       MOVE WS-CUSTNO TO WS-DTL-CUSTNO           (auto numeric -> alpha)
The ONE legitimate reason to add a new field is an edited display PIC
(PIC Z…, PIC -9…, PIC 99/99/9999, etc.) that COBOL needs for format
conversion — and even then, declare it ONCE, not per source field.

━━ PROGRAM SKELETON ━━
MAIN-PROCESS PERFORMS lower paragraphs (THRU para-EXIT form) and ends
with STOP RUN.  STOP RUN appears ONLY in MAIN-PROCESS.

       MAIN-PROCESS.
           PERFORM OPEN-FILES   THRU OPEN-FILES-EXIT
           PERFORM MAIN-LOGIC   THRU MAIN-LOGIC-EXIT
           PERFORM CLOSE-FILES  THRU CLOSE-FILES-EXIT
           STOP RUN.
       MAIN-PROCESS-EXIT.
           EXIT.

OPEN-FILES opens each file and checks its status; on failure DISPLAY
an error message and STOP RUN.  Use this exact shape for each file:

       OPEN-FILES.
           OPEN INPUT INFILE
           IF WS-INFILE-STATUS NOT = '00'
               DISPLAY 'ERROR OPENING INFILE STATUS: ' WS-INFILE-STATUS
               STOP RUN
           END-IF
           OPEN OUTPUT RPTFILE
           IF WS-RPTFILE-STATUS NOT = '00'
               DISPLAY 'ERROR OPENING RPTFILE STATUS: ' WS-RPTFILE-STATUS
               STOP RUN
           END-IF.
       OPEN-FILES-EXIT.
           EXIT.

CLOSE-FILES closes each file (one CLOSE per file, no status check
unless EZT explicitly cares).  MAIN-LOGIC drives a READ loop and calls
PROCESS-RECORD per record.  Any  PRINT <rpt>  in PROCESS-RECORD becomes
PERFORM <RPT>-PRINT-RTN THRU <RPT>-PRINT-RTN-EXIT.

Omit OPEN-FILES / CLOSE-FILES (and their PERFORMs from MAIN-PROCESS)
for JOB INPUT NULL.  Omit the READ loop for batch-compute programs.

━━ COBOL RULES ━━
Period rules (most critical):
  • One period ends each paragraph -- on its LAST statement.
  • That period is MANDATORY before the next paragraph header; without
    it the compiler glues them together and rejects the program.
  • NEVER put a period inside IF / EVALUATE / PERFORM / READ / WRITE.
    The period belongs after END-IF / END-PERFORM / etc.

Scope terminators are required: END-IF, END-EVALUATE, END-PERFORM,
END-READ, END-WRITE.

Every paragraph has a matching <PARA>-EXIT containing only EXIT.
Every PERFORM uses the THRU form.

Paragraph names cannot be COBOL reserved words.  Add a suffix:
  BAD:  INITIAL.   /  TERMINATE.
  GOOD: INIT-RTN.  /  TERM-RTN.  /  WRAP-UP.

━━ UNSUPPORTED FUNCTIONS ━━
Never emit FUNCTION MOD(x, y) -- not portable.  Use:
       COMPUTE WS-REM = WS-X - (FUNCTION INTEGER (WS-X / WS-Y)) * WS-Y
or, if FUNCTION INTEGER is unavailable:
       DIVIDE WS-X BY WS-Y GIVING WS-Q
       COMPUTE WS-REM = WS-X - (WS-Q * WS-Y)

━━ WHAT NOT TO OUTPUT ━━
  • Reasoning, preamble, summaries, markdown fences, non-COBOL text
  • IDENTIFICATION / ENVIRONMENT / DATA DIVISION headers
  • FILE / WORKING-STORAGE / LINKAGE SECTION headers
  • Any identifier already in the allow-list (redeclaration)
  • Any paragraph emitted more than once

Prior converted context (DATA DIVISION already generated):
{{context}}

EZT logic sections:
{{content}}
"""
